name: "Deploy to AWS S3"
description: 'Deploy a static wbsite via aws s3'
inputs:
  bucket:
    description: 'The S3 bucket name'
    required: true
  bucket-region:
    description: 'The S3 bucket version'
    required: false
    default: 'ap-southeast-1'
  dist-folder:
    description: 'The folder containing the deployable files'
    required: true
    default: 'dist'
outputs:
  website-url:
    description: 'URL for website'

runs:
  using: 'node24'
  main: 'index.js'
  