name: Events Demo 1
on: 
    pull_request:
        types: [opened, edited]
    workflow_dispatch:
    push:
        branches:
            - main
            - 'dev-*'
            - 'feature/*'
        paths-ignore:
            - 'docs/**'  # Nếu sửa trong docs/**, thì workflow sẽ không chạy 
                         # <=> ngược lại với "paths": Chỉ chạy workflow khi các file chỉ định bị thay đổi
jobs:
    deploy: 
        runs-on: ubuntu-latest
        steps:
            - name: Output event data
              run: echo "Github event:${{ toJson(github) }}"
            - name: Get code
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Build code
              run: npm run build
            - name: Test code
              run: npm run test
            - name: Deploy code
              run: echo "Deploying code ..."