name: Label Issues (Script Injection Example)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Assign label
        # env: 
        #   TITLE: ${{ github.event.issue.title }}
        # Tạo tên tile issues là " bug"; rm -rf /; echo "  " gây nhiễu cực mạnh => chạy câu lệnh rm-rf
        # nên đặt TITLE lên thành biến môi trường rồi truyền vào như cmt
        # run: |
        #   if [[ $TITLE == *"bug"* ]]; then
        #   echo "Issue is about a bug!"
        #   else
        #   echo "Issue is not about a bug"
        #   fi
        run: |
          issue_title="${{ github.event.issue.title }}"    
          if [[ "$issue_title" == *"bug"* ]]; then
          echo "Issue is about a bug!"
          else
          echo "Issue is not about a bug"
          fi